config/routes.rb
Rails.application.routes.draw do
  resources :job_pos
  resources :job_posts
  resources :job_postings
  resources :jobs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/job.rb
class Job < ApplicationRecord
  
end

app/models/job_po.rb
class JobPo < ApplicationRecord
end

app/models/job_post.rb
class JobPost < ApplicationRecord
end

app/models/job_posting.rb
class JobPosting < ApplicationRecord
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/job_pos_controller.rb
class JobPosController < ApplicationController
  before_action :set_job_po, only: %i[ show edit update destroy ]

  # GET /job_pos or /job_pos.json
  def index
    @job_pos = JobPo.all
  end

  # GET /job_pos/1 or /job_pos/1.json
  def show
  end

  # GET /job_pos/new
  def new
    @job_po = JobPo.new
  end

  # GET /job_pos/1/edit
  def edit
  end

  # POST /job_pos or /job_pos.json
  def create
    @job_po = JobPo.new(job_po_params)

    respond_to do |format|
      if @job_po.save
        format.html { redirect_to job_po_url(@job_po), notice: "Job po was successfully created." }
        format.json { render :show, status: :created, location: @job_po }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_po.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_pos/1 or /job_pos/1.json
  def update
    respond_to do |format|
      if @job_po.update(job_po_params)
        format.html { redirect_to job_po_url(@job_po), notice: "Job po was successfully updated." }
        format.json { render :show, status: :ok, location: @job_po }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_po.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_pos/1 or /job_pos/1.json
  def destroy
    @job_po.destroy

    respond_to do |format|
      format.html { redirect_to job_pos_url, notice: "Job po was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_po
      @job_po = JobPo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_po_params
      params.require(:job_po).permit(:ids, :title, :companyName, :url)
    end
end

app/controllers/job_postings_controller.rb
class JobPostingsController < ApplicationController
  before_action :set_job_posting, only: %i[ show edit update destroy ]

  # GET /job_postings or /job_postings.json
  def index
    @job_postings = JobPosting.all
  end

  # GET /job_postings/1 or /job_postings/1.json
  def show
  end

  # GET /job_postings/new
  def new
    @job_posting = JobPosting.new
  end

  # GET /job_postings/1/edit
  def edit
  end

  # POST /job_postings or /job_postings.json
  def create
    @job_posting = JobPosting.new(job_posting_params)

    respond_to do |format|
      if @job_posting.save
        format.html { redirect_to job_posting_url(@job_posting), notice: "Job posting was successfully created." }
        format.json { render :show, status: :created, location: @job_posting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_postings/1 or /job_postings/1.json
  def update
    respond_to do |format|
      if @job_posting.update(job_posting_params)
        format.html { redirect_to job_posting_url(@job_posting), notice: "Job posting was successfully updated." }
        format.json { render :show, status: :ok, location: @job_posting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_postings/1 or /job_postings/1.json
  def destroy
    @job_posting.destroy

    respond_to do |format|
      format.html { redirect_to job_postings_url, notice: "Job posting was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_posting
      @job_posting = JobPosting.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_posting_params
      params.require(:job_posting).permit(:title, :companyName, :url)
    end
end

app/controllers/job_posts_controller.rb
class JobPostsController < ApplicationController
  before_action :set_job_post, only: %i[ show edit update destroy ]

  # GET /job_posts or /job_posts.json
  def index
    @job_posts = JobPost.all
  end

  # GET /job_posts/1 or /job_posts/1.json
  def show
  end

  # GET /job_posts/new
  def new
    @job_post = JobPost.new
  end

  # GET /job_posts/1/edit
  def edit
  end

  # POST /job_posts or /job_posts.json
  def create
    @job_post = JobPost.new(job_post_params)

    respond_to do |format|
      if @job_post.save
        format.html { redirect_to job_post_url(@job_post), notice: "Job post was successfully created." }
        format.json { render :show, status: :created, location: @job_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_posts/1 or /job_posts/1.json
  def update
    respond_to do |format|
      if @job_post.update(job_post_params)
        format.html { redirect_to job_post_url(@job_post), notice: "Job post was successfully updated." }
        format.json { render :show, status: :ok, location: @job_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_posts/1 or /job_posts/1.json
  def destroy
    @job_post.destroy

    respond_to do |format|
      format.html { redirect_to job_posts_url, notice: "Job post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_post
      @job_post = JobPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_post_params
      params.require(:job_post).permit(:id, :title, :companyName, :url)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]

  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to job_url(@job), notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:title, :companyName, :url, :source)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_pos_helper.rb
module JobPosHelper
end

app/helpers/job_postings_helper.rb
module JobPostingsHelper
end

app/helpers/job_posts_helper.rb
module JobPostsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/job_pos/_form.html.erb
<%= form_with(model: job_po) do |form| %>
  <% if job_po.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_po.errors.count, "error") %> prohibited this job_po from being saved:</h2>

      <ul>
        <% job_po.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :ids, style: "display: block" %>
    <%= form.number_field :ids %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :companyName, style: "display: block" %>
    <%= form.text_field :companyName %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/job_pos/_job_po.html.erb
<div id="<%= dom_id job_po %>">
  <p>
    <strong>Ids:</strong>
    <%= job_po.ids %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= job_po.title %>
  </p>

  <p>
    <strong>Companyname:</strong>
    <%= job_po.companyName %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= job_po.url %>
  </p>

</div>

app/views/job_pos/edit.html.erb
<h1>Editing job po</h1>

<%= render "form", job_po: @job_po %>

<br>

<div>
  <%= link_to "Show this job po", @job_po %> |
  <%= link_to "Back to job pos", job_pos_path %>
</div>

app/views/job_pos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Job pos</h1>

<div id="job_pos">
  <% @job_pos.each do |job_po| %>
    <%= render job_po %>
    <p>
      <%= link_to "Show this job po", job_po %>
    </p>
  <% end %>
</div>

<%= link_to "New job po", new_job_po_path %>

app/views/job_pos/new.html.erb
<h1>New job po</h1>

<%= render "form", job_po: @job_po %>

<br>

<div>
  <%= link_to "Back to job pos", job_pos_path %>
</div>

app/views/job_pos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job_po %>

<div>
  <%= link_to "Edit this job po", edit_job_po_path(@job_po) %> |
  <%= link_to "Back to job pos", job_pos_path %>

  <%= button_to "Destroy this job po", @job_po, method: :delete %>
</div>

app/views/job_postings/_form.html.erb
<%= form_with(model: job_posting) do |form| %>
  <% if job_posting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_posting.errors.count, "error") %> prohibited this job_posting from being saved:</h2>

      <ul>
        <% job_posting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :companyName, style: "display: block" %>
    <%= form.text_field :companyName %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/job_postings/_job_posting.html.erb
<div id="<%= dom_id job_posting %>">
  <p>
    <strong>Title:</strong>
    <%= job_posting.title %>
  </p>

  <p>
    <strong>Companyname:</strong>
    <%= job_posting.companyName %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= job_posting.url %>
  </p>

</div>

app/views/job_postings/edit.html.erb
<h1>Editing job posting</h1>

<%= render "form", job_posting: @job_posting %>

<br>

<div>
  <%= link_to "Show this job posting", @job_posting %> |
  <%= link_to "Back to job postings", job_postings_path %>
</div>

app/views/job_postings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Job postings</h1>

<div id="job_postings">
  <% @job_postings.each do |job_posting| %>
    <%= render job_posting %>
    <p>
      <%= link_to "Show this job posting", job_posting %>
    </p>
  <% end %>
</div>

<%= link_to "New job posting", new_job_posting_path %>

app/views/job_postings/new.html.erb
<h1>New job posting</h1>

<%= render "form", job_posting: @job_posting %>

<br>

<div>
  <%= link_to "Back to job postings", job_postings_path %>
</div>

app/views/job_postings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job_posting %>

<div>
  <%= link_to "Edit this job posting", edit_job_posting_path(@job_posting) %> |
  <%= link_to "Back to job postings", job_postings_path %>

  <%= button_to "Destroy this job posting", @job_posting, method: :delete %>
</div>

app/views/job_posts/_form.html.erb
<%= form_with(model: job_post) do |form| %>
  <% if job_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job_post.errors.count, "error") %> prohibited this job_post from being saved:</h2>

      <ul>
        <% job_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :companyName, style: "display: block" %>
    <%= form.text_field :companyName %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/job_posts/_job_post.html.erb
<div id="<%= dom_id job_post %>">
  <p>
    <strong>Id:</strong>
    <%= job_post.id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= job_post.title %>
  </p>

  <p>
    <strong>Companyname:</strong>
    <%= job_post.companyName %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= job_post.url %>
  </p>

</div>

app/views/job_posts/edit.html.erb
<h1>Editing job post</h1>

<%= render "form", job_post: @job_post %>

<br>

<div>
  <%= link_to "Show this job post", @job_post %> |
  <%= link_to "Back to job posts", job_posts_path %>
</div>

app/views/job_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Job posts</h1>

<div id="job_posts">
  <% @job_posts.each do |job_post| %>
    <%= render job_post %>
    <p>
      <%= link_to "Show this job post", job_post %>
    </p>
  <% end %>
</div>

<%= link_to "New job post", new_job_post_path %>

app/views/job_posts/new.html.erb
<h1>New job post</h1>

<%= render "form", job_post: @job_post %>

<br>

<div>
  <%= link_to "Back to job posts", job_posts_path %>
</div>

app/views/job_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job_post %>

<div>
  <%= link_to "Edit this job post", edit_job_post_path(@job_post) %> |
  <%= link_to "Back to job posts", job_posts_path %>

  <%= button_to "Destroy this job post", @job_post, method: :delete %>
</div>

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :companyName, style: "display: block" %>
    <%= form.text_field :companyName %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :source, style: "display: block" %>
    <%= form.text_field :source %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>">
  <p>
    <strong>Title:</strong>
    <%= job.title %>
  </p>

  <p>
    <strong>Companyname:</strong>
    <%= job.companyName %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= job.url %>
  </p>

  <p>
    <strong>Source:</strong>
    <%= job.source %>
  </p>

</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Jobs</h1>

<div id="jobs">
  <% @jobs.each do |job| %>
    <%= render job %>
    <p>
      <%= link_to "Show this job", job %>
    </p>
  <% end %>
</div>

<%= link_to "New job", new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %>

  <%= button_to "Destroy this job", @job, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PathriseTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>